baseURL = "https://canonical.github.io/charm-eng-releases"
languageCode = "en-gb"
title = "Charm Engineering Releases"

[params]
author = "Canonical Ltd."
description = "The latest releases from each team, and their statuses."

[markup.goldmark.renderer]
unsafe= true